name: ToxiUI remove old artifacts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        age: '7 days'
        skip-recent: 1
